version: "3.8"

services:
  backend:
    build: ./backend
    container_name: capstone-backend
    ports:
      - "5000:5000"
    depends_on:
      - database

  frontend:
    build: ./frontend
    container_name: capstone-frontend
    ports:
      - "80:80"

  database:
    image: postgres:15
    container_name: capstone-db
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: appdb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

